name: powerloader
channels:
- conda-forge
dependencies:
  # libpowerloader
  - cmake
  - ninja
  - cxx-compiler
  - libcurl <=7.87
  - openssl
  - nlohmann_json
  - zchunk
  - spdlog
  - cpp-expected
  # powerloader
  - cli11
  - yaml-cpp
  # Tests
  - doctest
  - pytest
  - pyyaml
  - python
  - pybind11
  - requests
  - pytest-xprocess
