name: powerloader-dev
channels:
  - conda-forge
dependencies:
  # libpowerloader-static
  - vs2019_win-64
  - ninja
  - vcpkg
  - curl
  - cpp-expected
  - spdlog
  - nlohmann_json
  - zchunk-static
  # powerloader
  - cli11
  - yaml-cpp
  # Tests
  - doctest
